language: python

python:
  - 3.7

install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install coverage

script:
  - pytest --cov=src tests/tests.py

after_success:
  - coveralls
